
skillMetadata:
  sections:
    - name: Telegram Bot Options
      fields:
        - type: label
          label: Telegram Bot Token
        - name: bottoken
          type: text
          label: Telegram Bot Token
          value: ""
        - name: adminchatid
          type: text
          label: Admin Chat ID
          value: ""
